version: 2
updates:
- package-ecosystem: "nuget"
  directory: "/"
  groups:
    all-dependencies:
      patterns:
      - "*"
  schedule:
    interval: "daily"
  reviewers:
  - "dnperfors"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
  - "dnperfors"
